services:
  DB:
    build: .
    volumes:
      - ./DB/benchmark.db:/app/DB/benchmark.db
    ports:
      - "5000:5000"

    
  benchmark:



  embedding-api:
    image: michaelf34/infinity:latest
    command: "--model-name-or-path /models/e5-large-v2 --port 80"
    volumes:
      - ./models:/models
    ports:
      - 5001:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]